version: '3.8'
services:
  # API Database
  postgres:
    image: postgres
    restart: always
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # Tests Database
  postgres-tests:
    image: postgres
    restart: always
    container_name: ${TEST_CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
    ports:
      - '5433:5432'

volumes:
  postgres: